### ISSUE TITLE
Getting attribute values for public key returns error

### ISSUE THREAD

**Issue by microshine** [open-eid/esteid-pkcs11#5]
`C_GetAttributeValue` returns error `CKR_ATTRIBUTE_TYPE_INVALID` for attribute `CKA_VERIFY`. Should it return false in this case if you don't set this property to `true`? I think I'll get the same error for `CKA_WRAP`.

**Comment by metsma** [comment]
esteid-pkcs11 is discontinued and replaced with opensc
